<?php
declare(strict_types=1);

/**
 * Safe cPanel deployment for a verified artifact.
 *
 *   1. Check the private config: outside the target, this channel's
 *      environment, MySQL, no placeholders.
 *   2. Verify the artifact against the checked source. Reject = nothing copied.
 *   3. Stage a copy outside the docroot and verify the staged copy.
 *   4. Install file by file with atomic renames. Runtime uploads are never
 *      written, replaced, or deleted; uploads/.htaccess is created only if absent.
 *   5. Verify the installed tree and confirm the uploads inventory is unchanged.
 *
 *   php scripts/deploy/cpanel-deploy.php --channel=staging --target=<docroot> \
 *       --private-config=<file outside docroot> [--source=<repo>] [--dist=<dir>] [--state=<dir>]
 */

require __DIR__ . '/../release/lib.php';

const DEPLOY_SELECTOR_RELATIVE = 'api/deployment.php';

function deploy_abort(string $message, int $status = 1): void
{
    fwrite(STDERR, 'DEPLOY ABORTED: ' . $message . PHP_EOL);
    exit($status);
}

function deploy_path_key(string $path): string
{
    $real = realpath($path);
    $value = str_replace('\\', '/', $real !== false ? $real : $path);

    return DIRECTORY_SEPARATOR === '\\' ? strtolower($value) : $value;
}

function deploy_path_within(string $path, string $root): bool
{
    $child = rtrim(deploy_path_key($path), '/') . '/';
    $parent = rtrim(deploy_path_key($root), '/') . '/';

    return strncmp($child, $parent, strlen($parent)) === 0;
}

/** Problems are reported by rule only; values from the private file are never printed. @return list<string> */
function deploy_private_config_problems(string $file, string $channel, string $target): array
{
    if (deploy_path_within($file, $target)) {
        return ['private config must be outside the document root'];
    }

    $loaded = (static function (string $__file) {
        return require $__file;
    })($file);
    if (!is_array($loaded)) {
        return ['private config must return an array'];
    }

    $problems = [];
    if (($loaded['environment'] ?? null) !== $channel) {
        $problems[] = 'private config environment does not match the deployment channel';
    }
    if (($loaded['db_driver'] ?? null) !== 'mysql') {
        $problems[] = 'deployed environments require mysql';
    }
    foreach (['db_name', 'db_user', 'app_url'] as $key) {
        if (trim((string) ($loaded[$key] ?? '')) === '') {
            $problems[] = "{$key} is required";
        }
    }
    foreach ($loaded as $key => $value) {
        if (is_string($value) && strpos(trim($value), 'REPLACE_') === 0) {
            $problems[] = "{$key} still contains a placeholder";
        }
    }
    if (!preg_match('#^https://#i', trim((string) ($loaded['app_url'] ?? '')))) {
        $problems[] = 'app_url must be https';
    }

    return $problems;
}

function deploy_selector_source(string $channel, string $privateConfig): string
{
    return "<?php\n"
        . "// Generated by scripts/deploy/cpanel-deploy.php. Preserved across deploys; never commit.\n"
        . "if (!defined('AAPM_DEPLOYMENT_SELECTOR_LOADING')) {\n"
        . "    http_response_code(404);\n"
        . "    exit;\n"
        . "}\n\n"
        . "return [\n"
        . "    'environment' => " . var_export($channel, true) . ",\n"
        . "    'config_path' => " . var_export($privateConfig, true) . ",\n"
        . "];\n";
}

function deploy_copy_file(string $from, string $to): void
{
    $directory = dirname($to);
    if (!is_dir($directory) && !mkdir($directory, 0775, true)) {
        deploy_abort('cannot create directory for ' . basename($to));
    }
    if (!copy($from, $to)) {
        deploy_abort('copy failed for ' . basename($to));
    }
}

/** Writes through a temporary sibling and renames, so readers never see a partial file. */
function deploy_install_file(string $from, string $to): void
{
    $directory = dirname($to);
    if (!is_dir($directory) && !mkdir($directory, 0775, true)) {
        deploy_abort('cannot create directory for ' . basename($to));
    }
    $temp = $to . '.aapm-tmp-' . bin2hex(random_bytes(6));
    if (!copy($from, $temp)) {
        @unlink($temp);
        deploy_abort('copy failed for ' . basename($to));
    }
    if (!rename($temp, $to)) {
        @unlink($temp);
        deploy_abort('rename failed for ' . basename($to));
    }
}

function deploy_write_text(string $to, string $content): void
{
    $temp = $to . '.aapm-tmp-' . bin2hex(random_bytes(6));
    if (file_put_contents($temp, $content) === false) {
        @unlink($temp);
        deploy_abort('cannot write ' . basename($to));
    }
    if (!rename($temp, $to)) {
        @unlink($temp);
        deploy_abort('rename failed for ' . basename($to));
    }
}

function deploy_remove_tree(string $directory): void
{
    if (!is_dir($directory)) {
        return;
    }
    $items = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($directory, FilesystemIterator::SKIP_DOTS),
        RecursiveIteratorIterator::CHILD_FIRST
    );
    foreach ($items as $item) {
        if ($item->isDir()) {
            rmdir($item->getPathname());
        } else {
            unlink($item->getPathname());
        }
    }
    rmdir($directory);
}

/** Size and modification time of every upload except the control file. Any change is treated as a violation. */
function deploy_uploads_inventory(string $target): array
{
    $inventory = [];
    foreach (aapm_release_list_files($target, 'uploads') as $path) {
        if ($path === 'uploads/.htaccess') {
            continue;
        }
        $absolute = $target . '/' . $path;
        $inventory[$path] = filesize($absolute) . ':' . filemtime($absolute);
    }
    ksort($inventory);

    return $inventory;
}

/** @return list<string> */
function deploy_installed_problems(string $target, array $manifest, string $selectorContent, array $contract): array
{
    $problems = [];
    foreach ($manifest['files'] as $entry) {
        $path = (string) $entry['path'];
        if (strpos($path, 'uploads/') === 0) {
            continue;
        }
        $absolute = $target . '/' . $path;
        if (!is_file($absolute)) {
            $problems[] = "missing: {$path}";
        } elseif (aapm_release_content_hash($absolute, $contract) !== $entry['sha256']) {
            $problems[] = "differs: {$path}";
        }
    }
    $selector = $target . '/' . DEPLOY_SELECTOR_RELATIVE;
    if (!is_file($selector) || file_get_contents($selector) !== $selectorContent) {
        $problems[] = 'deployment selector not written';
    }
    if (!is_file($target . '/uploads/.htaccess')) {
        $problems[] = 'uploads/.htaccess missing';
    }

    return $problems;
}

$options = getopt('', ['channel:', 'target:', 'private-config:', 'source::', 'dist::', 'state::']);
foreach (['channel', 'target', 'private-config'] as $name) {
    if (!isset($options[$name]) || $options[$name] === false || $options[$name] === '') {
        deploy_abort("--{$name} is required", 2);
    }
}

$channel = (string) $options['channel'];
if (!in_array($channel, ['staging', 'production'], true)) {
    deploy_abort('--channel must be staging or production', 2);
}
$target = realpath((string) $options['target']);
if ($target === false || !is_dir($target)) {
    deploy_abort('target directory does not exist', 2);
}
$privateConfig = realpath((string) $options['private-config']);
if ($privateConfig === false || !is_file($privateConfig)) {
    deploy_abort('private config file not found', 2);
}
$sourceRoot = realpath((string) (($options['source'] ?? false) ?: dirname(__DIR__, 2)));
if ($sourceRoot === false) {
    deploy_abort('source directory not found', 2);
}
$distRoot = realpath((string) (($options['dist'] ?? false) ?: $sourceRoot . '/dist'));
if ($distRoot === false || !is_dir($distRoot)) {
    deploy_abort('dist directory not found', 2);
}
$stateOption = (string) (($options['state'] ?? false) ?: (getenv('HOME') ?: sys_get_temp_dir()) . '/.aapm-release-state');
if (!is_dir($stateOption) && !mkdir($stateOption, 0775, true)) {
    deploy_abort('cannot create state directory', 2);
}
$stateRoot = realpath($stateOption);
if ($stateRoot === false || deploy_path_within($stateRoot, $target)) {
    deploy_abort('state directory must exist outside the target', 2);
}

// 1. Private configuration for this channel.
$configProblems = deploy_private_config_problems($privateConfig, $channel, $target);
if ($configProblems !== []) {
    foreach ($configProblems as $problem) {
        fwrite(STDERR, "private config: {$problem}\n");
    }
    deploy_abort('private configuration is not ready; nothing was copied', 1);
}

// 2. Artifact verification against the checked source. Nothing is copied on failure.
$contract = aapm_release_contract($sourceRoot);
$verdict = aapm_release_verify($distRoot, $sourceRoot, $contract, $channel);
if (!$verdict['ok']) {
    foreach ($verdict['errors'] as $error) {
        fwrite(STDERR, sprintf("[%s] %s: %s\n", $error['code'], $error['path'] ?? '', $error['detail']));
    }
    deploy_abort('artifact rejected; nothing was copied', 1);
}

// 3. Staged copy outside the docroot, verified before it touches the target.
$stage = $stateRoot . '/' . $channel . '/stage';
deploy_remove_tree($stage);
mkdir($stage, 0775, true);
$payload = array_merge(
    array_values(array_filter(
        aapm_release_distribution_files($distRoot),
        static function (string $path) use ($contract): bool {
            return strpos($path, 'uploads/') !== 0 || in_array($path, $contract['artifact']['uploadsAllowed'], true);
        }
    )),
    [AAPM_RELEASE_MANIFEST_FILE]
);
foreach ($payload as $path) {
    deploy_copy_file($distRoot . '/' . $path, $stage . '/' . $path);
}
$stageVerdict = aapm_release_verify($stage, $sourceRoot, $contract, $channel);
if (!$stageVerdict['ok']) {
    deploy_abort('staged copy failed verification; the target was not changed', 1);
}
$manifest = json_decode((string) file_get_contents($stage . '/' . AAPM_RELEASE_MANIFEST_FILE), true);

// 4. Install. Uploads are only inventoried here, never written except the control file.
$uploadsBefore = deploy_uploads_inventory($target);
foreach ($manifest['files'] as $entry) {
    $path = (string) $entry['path'];
    if (strpos($path, 'uploads/') === 0) {
        continue;
    }
    deploy_install_file($stage . '/' . $path, $target . '/' . $path);
}
deploy_install_file($stage . '/' . AAPM_RELEASE_MANIFEST_FILE, $target . '/' . AAPM_RELEASE_MANIFEST_FILE);
$selectorContent = deploy_selector_source($channel, $privateConfig);
deploy_write_text($target . '/' . DEPLOY_SELECTOR_RELATIVE, $selectorContent);
if (!is_dir($target . '/uploads') && !mkdir($target . '/uploads', 0775, true)) {
    deploy_abort('cannot create uploads directory');
}
if (!is_file($target . '/uploads/.htaccess')) {
    deploy_install_file($stage . '/uploads/.htaccess', $target . '/uploads/.htaccess');
}

// 5. Verify the installed tree. A partial install reports as incomplete, never as success.
$installProblems = deploy_installed_problems($target, $manifest, $selectorContent, $contract);
if ($installProblems !== []) {
    foreach ($installProblems as $problem) {
        fwrite(STDERR, "installed: {$problem}\n");
    }
    deploy_abort('release incomplete: installed tree does not match the artifact', 1);
}
if (deploy_uploads_inventory($target) !== $uploadsBefore) {
    deploy_abort('uploads changed during deployment; investigate before continuing', 1);
}

$receipt = [
    'channel' => $channel,
    'artifactId' => $manifest['artifactId'],
    'sourceTreeFingerprint' => $manifest['sourceTreeFingerprint'],
    'sourceCommit' => $manifest['sourceCommit'],
    'deployedAt' => gmdate('c'),
    'files' => count($manifest['files']),
    'uploadsPreserved' => count($uploadsBefore),
];
file_put_contents(
    $stateRoot . '/' . $channel . '/last-deploy.json',
    json_encode($receipt, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) . PHP_EOL
);

echo sprintf(
    "deployed channel=%s artifact=%s files=%d uploads-preserved=%d\n",
    $channel,
    $manifest['artifactId'],
    count($manifest['files']),
    count($uploadsBefore)
);
exit(0);
