<?php

function native_seed_video_url(int $moduleNumber): string
{
    static $videos = [
        1 => 'https://www.youtube.com/watch?v=CCzevPhnGug',
        2 => 'https://www.youtube.com/watch?v=WDTqNVn7tes',
        3 => 'https://www.youtube.com/watch?v=M779w9jCmZA',
        4 => 'https://www.youtube.com/watch?v=M779w9jCmZA',
        5 => 'https://www.youtube.com/watch?v=WDTqNVn7tes',
        6 => 'https://www.youtube.com/watch?v=lIHkrDIh4O8',
        7 => 'https://www.youtube.com/watch?v=lIHkrDIh4O8',
        8 => 'https://www.youtube.com/watch?v=V_EellDKgRs',
        9 => 'https://www.youtube.com/watch?v=Q1lDTpEXmIc',
        10 => 'https://www.youtube.com/watch?v=Q1lDTpEXmIc',
        11 => 'https://www.youtube.com/watch?v=lIHkrDIh4O8',
        12 => 'https://www.youtube.com/watch?v=aUckv3knhms',
        13 => 'https://www.youtube.com/watch?v=WDTqNVn7tes',
        14 => 'https://www.youtube.com/watch?v=lIHkrDIh4O8',
        15 => 'https://www.youtube.com/watch?v=lIHkrDIh4O8',
        16 => 'https://www.youtube.com/watch?v=CCzevPhnGug',
        17 => 'https://www.youtube.com/watch?v=CCzevPhnGug',
        18 => 'https://www.youtube.com/watch?v=CCzevPhnGug',
        19 => 'https://www.youtube.com/watch?v=lIHkrDIh4O8',
        20 => 'https://www.youtube.com/watch?v=lIHkrDIh4O8',
        21 => 'https://www.youtube.com/watch?v=CCzevPhnGug',
        22 => 'https://www.youtube.com/watch?v=CCzevPhnGug',
    ];

    return $videos[$moduleNumber] ?? '';
}

function native_seed_module(
    int $level,
    string $levelName,
    int $moduleNumber,
    string $title,
    string $category,
    string $summary,
    string $content,
    array $objectives,
    array $takeaways,
    array $checklist,
    string $assignment
): array {
    return [
        'level_number' => $level,
        'level_name' => $levelName,
        'module_number' => $moduleNumber,
        'title' => $title,
        'category' => $category,
        'summary' => $summary,
        'content' => $content,
        'video_script' => "Pada lesson ini kita membahas {$title}. Fokuskan pengamatan pada proses, angka KPI, dan tindakan koreksi yang bisa diterapkan di farm.",
        'video_url' => native_seed_video_url($moduleNumber),
        'learning_objectives' => $objectives,
        'key_takeaways' => $takeaways,
        'checklist' => $checklist,
        'practical_assignment' => $assignment,
        'sort_order' => $moduleNumber,
    ];
}

function native_seed_question(
    int $moduleNumber,
    string $question,
    array $options,
    int $correctIndex,
    string $explanation,
    string $difficulty = 'medium',
    string $type = 'mcq'
): array {
    return [
        'module_number' => $moduleNumber,
        'question' => $question,
        'options' => $options,
        'correct_index' => $correctIndex,
        'explanation' => $explanation,
        'difficulty' => $difficulty,
        'type' => $type,
        'learning_objective' => 'Menerapkan prinsip dasar manajemen layer farm.',
    ];
}

return [
    'modules' => [
        native_seed_module(1, 'Foundation', 1, 'Dasar Manajemen Layer Farm', 'Foundation', 'Peta besar bisnis dan operasional ayam petelur komersial dari DOC sampai afkir.',
            "## Mengapa sistem penting?\n\nLayer farm adalah rangkaian proses yang saling terkait: **bibit, lingkungan, pakan, air, kesehatan, tenaga kerja, data, dan ekonomi**. Setiap keputusan perlu dicatat agar bisa dibandingkan dengan target dan minggu sebelumnya.\n\nMulailah dari SOP sederhana, pembagian tanggung jawab, serta definisi KPI yang konsisten.",
            ['Memahami alur produksi layer.', 'Mengenali komponen utama biaya dan risiko.', 'Membuat daftar KPI operasional awal.'],
            ['Data yang konsisten lebih berguna daripada data yang banyak.', 'SOP harus dapat diamati dan diaudit.', 'Kinerja farm adalah hasil interaksi banyak faktor.'],
            ['Petakan alur DOC sampai afkir.', 'Tentukan PIC untuk pakan, air, kesehatan, dan data.', 'Buat daftar KPI harian dan mingguan.'],
            'Buat satu halaman peta proses farm dan tuliskan tiga titik risiko terbesar.'),
        native_seed_module(1, 'Foundation', 2, 'Siklus Hidup Ayam Petelur', 'Foundation', 'Memahami fase brooding, growing, pre-lay, produksi, post-peak, dan afkir.',
            "## Fase utama\n\nSetiap fase memiliki target bobot badan, uniformity, konsumsi pakan, dan respons terhadap cahaya yang berbeda. Kesalahan di fase awal sering terlihat sebagai masalah produksi beberapa minggu kemudian.\n\nGunakan umur ayam sebagai sumbu utama saat membaca performa.",
            ['Membedakan target tiap fase.', 'Menghubungkan pertumbuhan dengan kesiapan produksi.', 'Menyusun kalender monitoring umur ayam.'],
            ['Fase pullet menentukan potensi layer.', 'Transisi pakan harus mengikuti umur dan bobot.', 'Jangan membandingkan KPI lintas fase tanpa konteks.'],
            ['Tulis target monitoring per fase.', 'Tandai jadwal transfer dan perubahan pakan.', 'Catat deviasi dari target.'],
            'Buat kalender 0–80 minggu yang memuat fase, target utama, dan jadwal monitoring.'),
        native_seed_module(2, 'Brooding & Rearing', 3, 'Brooding: DOC sampai 6 Minggu', 'Brooding', 'Fondasi brooding: suhu, akses pakan-air, crop fill, mortalitas, dan uniformity awal.',
            "## Prioritas brooding\n\nPada minggu awal, target utama adalah DOC cepat menemukan pakan dan air, suhu merata, litter kering, serta perilaku ayam aktif. Periksa crop fill, distribusi ayam, dan mortalitas beberapa kali sehari.\n\nCatat hasil inspeksi sehingga perubahan bisa dikoreksi sebelum menjadi gap pertumbuhan.",
            ['Menentukan prioritas 24 jam pertama.', 'Memantau suhu dan perilaku ayam.', 'Menggunakan crop fill dan uniformity sebagai indikator.'],
            ['Akses air adalah prioritas segera setelah datang.', 'Perilaku dan sebaran ayam memberi sinyal suhu.', 'Mortalitas perlu dicatat dengan sebab yang mungkin.'],
            ['Cek sebaran ayam di beberapa titik.', 'Ukur suhu di level ayam.', 'Dokumentasikan crop fill dan mortalitas.'],
            'Lakukan audit brooding menggunakan checklist 10 poin dan beri skor kepatuhan.'),
        native_seed_module(2, 'Brooding & Rearing', 4, 'Growing & Rearing: 7–17 Minggu', 'Growing', 'Mengelola pertumbuhan pullet agar bobot badan dan uniformity siap masuk fase produksi.',
            "## Pertumbuhan yang seragam\n\nPullet yang seragam lebih mudah merespons program pencahayaan dan pakan. Timbang sampel secara konsisten, hitung persentase ayam dalam rentang ±10% dari rata-rata, lalu tindak lanjuti kelompok yang tertinggal.\n\nKepadatan, akses feeder, kualitas air, dan kesehatan saling memengaruhi.",
            ['Menghitung uniformity sederhana.', 'Mengidentifikasi penyebab pertumbuhan tidak seragam.', 'Menetapkan tindakan koreksi berbasis data.'],
            ['Uniformity menunjukkan keseragaman flock, bukan hanya rata-rata.', 'Akses feeder dan air harus merata.', 'Koreksi dini lebih murah daripada koreksi saat produksi.'],
            ['Timbang sampel mingguan.', 'Hitung uniformity.', 'Periksa ruang feeder dan nipple.'],
            'Hitung uniformity dari sampel 100 ekor dan susun rencana koreksinya.'),
        native_seed_module(3, 'Layer Management', 5, 'Persiapan Pre-Lay dan Transfer', 'Pre-Lay', 'Mempersiapkan ayam menuju produksi melalui transisi pakan, cahaya, dan perpindahan kandang.',
            "## Transisi yang terkendali\n\nFase pre-lay adalah jembatan dari pertumbuhan ke produksi. Hindari perubahan mendadak. Pastikan bobot badan, tulang medullary, konsumsi pakan, dan kesiapan kandang mendukung awal produksi.\n\nRencanakan transfer agar stres, kehilangan bobot, dan gangguan konsumsi dapat ditekan.",
            ['Menyusun rencana transisi.', 'Menghubungkan bobot badan dengan kesiapan produksi.', 'Menyiapkan checklist transfer.'],
            ['Transisi bertahap menjaga konsumsi.', 'Kandang produksi harus siap sebelum ayam datang.', 'Pantau intake dan mortalitas pascatransfer.'],
            ['Verifikasi kesiapan kandang.', 'Catat bobot sebelum dan sesudah transfer.', 'Pantau 7 hari pertama.'],
            'Buat SOP transfer pullet dengan pembagian peran dan indikator keberhasilan.'),
        native_seed_module(3, 'Layer Management', 6, 'Manajemen Produksi Layer', 'Production', 'Mengelola peak production, post-peak, egg mass, dan keputusan operasional harian.',
            "## Membaca produksi\n\nHDP, egg weight, egg mass, feed intake, mortality, dan FCR perlu dibaca bersama. Kenaikan satu indikator belum tentu berarti kinerja lebih baik jika ada penurunan kualitas telur atau biaya.\n\nGunakan tren mingguan untuk menentukan prioritas tindakan.",
            ['Menghitung egg mass.', 'Membaca hubungan produksi dan intake.', 'Membuat rapat produksi berbasis KPI.'],
            ['HDP harus dibaca bersama egg weight.', 'Peak bukan satu-satunya target.', 'Tindakan koreksi harus memiliki PIC dan tenggat.'],
            ['Review KPI harian.', 'Bandingkan dengan target umur.', 'Catat tindakan koreksi dan hasilnya.'],
            'Buat template rapat produksi mingguan yang berisi KPI, gap, penyebab, dan tindakan.'),
        native_seed_module(4, 'Nutrition', 7, 'Nutrisi dan Formulasi Pakan', 'Nutrition', 'Dasar kebutuhan energi, protein, mineral, dan kualitas pakan untuk layer.',
            "## Pakan sebagai investasi\n\nFormulasi harus mengikuti fase, konsumsi aktual, kualitas bahan, dan target produksi. Perhatikan energi, asam amino, kalsium, fosfor, serta bentuk fisik pakan.\n\nKontrol penerimaan bahan, penyimpanan, distribusi, dan sisa pakan sama pentingnya dengan formula.",
            ['Memahami komponen nutrisi utama.', 'Mengidentifikasi risiko kualitas bahan.', 'Menghubungkan intake dengan egg mass dan FCR.'],
            ['Kualitas bahan dapat berubah antar lot.', 'Distribusi pakan memengaruhi uniformity.', 'FCR harus dianalisis bersama egg mass.'],
            ['Periksa gudang dan FIFO.', 'Catat feed intake harian.', 'Audit distribusi feeder.'],
            'Buat checklist penerimaan dan penyimpanan bahan pakan.'),
        native_seed_module(5, 'Water Management', 8, 'Air Minum dan Water Management', 'Water', 'Menjamin kuantitas, kualitas, tekanan, dan kebersihan air minum.',
            "## Air adalah KPI awal\n\nPerubahan konsumsi air sering muncul sebelum perubahan produksi. Periksa debit nipple, kebocoran, kualitas mikrobiologi, pH, dan akses di seluruh kandang.\n\nBandingkan water-to-feed ratio dengan suhu dan kondisi flock.",
            ['Mengukur konsumsi air.', 'Mengecek sistem nipple dan reservoir.', 'Menyusun tindakan ketika ratio berubah.'],
            ['Air bersih dan tersedia sepanjang waktu.', 'Kebocoran meningkatkan kelembapan litter.', 'Perubahan ratio perlu konteks lingkungan.'],
            ['Uji beberapa titik nipple.', 'Catat meter air harian.', 'Cek kebocoran dan end-line.'],
            'Buat audit sistem air dari sumber sampai titik minum terakhir.'),
        native_seed_module(6, 'Environment & Closed House', 9, 'Suhu, Kelembapan, dan Ventilasi', 'Environment', 'Mengatur mikroklimat untuk kenyamanan ayam dan kualitas litter.',
            "## Mikroklimat\n\nAyam merespons gabungan suhu, kelembapan, kecepatan udara, dan kualitas udara. Suhu di luar tidak cukup untuk menggambarkan kondisi di level ayam.\n\nGunakan pengukuran beberapa titik dan hubungkan dengan perilaku flock.",
            ['Mengukur mikroklimat dengan benar.', 'Menghubungkan lingkungan dengan konsumsi.', 'Mengenali sinyal heat stress.'],
            ['Ukur di level ayam.', 'Ventilasi harus membuang panas dan gas.', 'Perubahan perilaku adalah indikator awal.'],
            ['Catat suhu dan RH pagi-siang-malam.', 'Periksa inlet dan kipas.', 'Amati panting dan sebaran ayam.'],
            'Buat peta titik ukur suhu/RH dan jadwal pencatatannya.'),
        native_seed_module(6, 'Environment & Closed House', 10, 'Closed House & Lighting Program', 'Closed House', 'Memahami kontrol cahaya, tekanan udara, inlet, fan, dan program ventilasi.',
            "## Sistem tertutup\n\nClosed house bekerja sebagai sistem: kapasitas fan, inlet, static pressure, blackout, pencahayaan, dan alarm. Perubahan kecil dapat berdampak pada konsumsi dan perilaku.\n\nSemua set point perlu dicatat bersama kondisi aktual.",
            ['Mengenali komponen closed house.', 'Menyusun pemeriksaan fan dan inlet.', 'Membaca program pencahayaan.'],
            ['Kapasitas fan harus sesuai beban.', 'Alarm dan generator adalah pengaman kritis.', 'Set point harus diverifikasi di lapangan.'],
            ['Tes alarm dan generator.', 'Bersihkan fan dan inlet.', 'Catat lux di beberapa titik.'],
            'Susun checklist inspeksi closed house sebelum dan sesudah shift.'),
        native_seed_module(7, 'Health & Veterinary', 11, 'Kesehatan, Vaksinasi, dan Monitoring', 'Health', 'Membangun sistem monitoring kesehatan dan koordinasi dengan dokter hewan.',
            "## Deteksi dini\n\nPantau konsumsi, mortalitas, feses, suara, perilaku, produksi, dan kualitas telur. Data membantu menentukan kapan perlu eskalasi. Diagnosis dan terapi harus ditetapkan oleh dokter hewan yang bertanggung jawab.\n\nSimpan catatan vaksinasi, obat, dan withdrawal period.",
            ['Membuat indikator kesehatan harian.', 'Membaca perubahan normal vs abnormal.', 'Mendokumentasikan program kesehatan.'],
            ['Data harian mempercepat deteksi.', 'Jangan menebak diagnosis dari satu gejala.', 'Withdrawal period wajib dipatuhi.'],
            ['Review mortalitas dan culling.', 'Cek catatan vaksinasi.', 'Eskalasi kasus sesuai SOP.'],
            'Buat form monitoring kesehatan dan alur eskalasi ke dokter hewan.'),
        native_seed_module(8, 'Biosecurity', 12, 'Biosecurity Operasional', 'Biosecurity', 'Mencegah masuk dan menyebarnya penyakit melalui orang, kendaraan, alat, dan hewan liar.',
            "## Lapisan biosecurity\n\nBiosecurity mencakup isolasi lokasi, kontrol akses, kebersihan, disinfeksi, pengendalian hama, dan alur bersih-kotor. Prosedur harus mudah dilakukan dan diawasi.\n\nDokumentasi membuat kepatuhan dapat diukur.",
            ['Memetakan sumber risiko.', 'Membuat prosedur akses dan sanitasi.', 'Mengukur kepatuhan biosecurity.'],
            ['Biosecurity adalah kebiasaan harian.', 'Footbath harus aktif, bukan sekadar ada.', 'Tamu dan kendaraan harus tercatat.'],
            ['Audit pintu masuk.', 'Cek footbath.', 'Periksa rodent bait station.'],
            'Lakukan audit biosecurity menggunakan skor risiko per area.'),
        native_seed_module(9, 'Egg Management', 13, 'Egg Collection & Egg Quality', 'Egg Quality', 'Mengurangi retak, kotor, pecah, dan penurunan kualitas selama pengumpulan serta penyimpanan.',
            "## Kualitas telur\n\nKualitas dimulai dari kesehatan dan nutrisi, lalu dipengaruhi oleh desain nest, frekuensi collection, handling, grading, serta suhu penyimpanan. Bedakan kerusakan dari sumbernya agar tindakan tepat.\n\nCatat persentase telur reject dan penyebabnya.",
            ['Mengelompokkan cacat telur.', 'Menganalisis titik kerusakan.', 'Menyusun tindakan pencegahan.'],
            ['Reject perlu dibedakan berdasarkan sebab.', 'Handling kasar meningkatkan retak.', 'Penyimpanan memengaruhi mutu konsumen.'],
            ['Cek nest dan conveyor.', 'Catat reject harian.', 'Audit cara handling.'],
            'Buat Pareto cacat telur selama satu minggu dan rekomendasi perbaikannya.'),
        native_seed_module(10, 'Farm Data & KPI', 14, 'Data Produksi dan KPI Dasar', 'KPI', 'Membuat data production record yang konsisten dan bisa ditindaklanjuti.',
            "## Data yang bisa dipercaya\n\nTetapkan definisi setiap KPI, satuan, waktu pencatatan, sumber data, dan siapa yang memverifikasi. Hindari angka tanpa konteks umur, populasi, dan periode.\n\nDashboard harus membantu keputusan, bukan menambah beban administrasi.",
            ['Mendefinisikan KPI.', 'Membedakan data primer dan turunan.', 'Membuat ritme review.'],
            ['Satuan dan definisi harus konsisten.', 'Data anomali perlu ditandai.', 'KPI dipakai untuk tindakan.'],
            ['Verifikasi populasi.', 'Cek kelengkapan record.', 'Review tren mingguan.'],
            'Buat data dictionary untuk semua kolom KPI dashboard.'),
        native_seed_module(10, 'Farm Data & KPI', 15, 'FCR, Egg Mass, dan Benchmarking', 'KPI', 'Menghitung egg mass dan FCR dengan definisi yang konsisten untuk perbandingan.',
            "## Membandingkan secara adil\n\nEgg mass menggabungkan HDP dan berat telur. FCR membandingkan feed intake dengan egg mass. Pastikan periode, populasi, dan satuan sama sebelum membandingkan antar kandang atau farm.\n\nGunakan benchmark sebagai sinyal investigasi, bukan target buta.",
            ['Menghitung egg mass.', 'Menghitung FCR.', 'Menetapkan benchmark yang relevan.'],
            ['Rumus sederhana tetap membutuhkan data bersih.', 'Benchmark harus sebanding.', 'Gap perlu root cause analysis.'],
            ['Validasi feed intake.', 'Validasi egg weight.', 'Bandingkan antar minggu.'],
            'Gunakan data KPI sendiri untuk menghitung FCR dan jelaskan dua penyebab gap.'),
        native_seed_module(11, 'Farm Economics', 16, 'Ekonomi Farm: Revenue dan Cost', 'Economics', 'Memahami arus pendapatan, biaya pakan, tenaga kerja, energi, kesehatan, dan biaya tersembunyi.',
            "## Profit bukan hanya omzet\n\nRevenue harus dibaca bersama biaya langsung dan biaya tetap. Pakan biasanya menjadi komponen besar, tetapi mortalitas, reject telur, energi, dan downtime juga menggerus margin.\n\nPisahkan biaya yang dapat dikendalikan dan yang perlu dikelola risikonya.",
            ['Mengelompokkan revenue dan cost.', 'Mengenali cost driver.', 'Membuat review margin.'],
            ['Omzet tinggi tidak otomatis profit tinggi.', 'Cost per egg membantu perbandingan.', 'Biaya kehilangan perlu diukur.'],
            ['Kumpulkan biaya mingguan.', 'Hitung revenue bersih.', 'Tandai deviasi terbesar.'],
            'Buat laporan sederhana revenue-cost per minggu dan tuliskan tiga cost driver.'),
        native_seed_module(11, 'Farm Economics', 17, 'Break Even, ROI, dan Cashflow', 'Economics', 'Menggunakan kalkulator ekonomi untuk keputusan investasi dan operasional.',
            "## Keputusan berbasis margin\n\nBreak even point bergantung pada CAPEX dan margin. ROI membantu membandingkan peluang, tetapi cashflow dan risiko operasional tetap harus dinilai.\n\nGunakan skenario konservatif, dasar, dan optimistis.",
            ['Menghitung margin.', 'Menghitung BEP dan ROI.', 'Menyusun skenario sederhana.'],
            ['Asumsi harus ditulis.', 'Margin dan cashflow berbeda.', 'Risiko juga bagian dari keputusan.'],
            ['Tentukan asumsi harga.', 'Hitung tiga skenario.', 'Review sensitivitas pakan dan produksi.'],
            'Gunakan kalkulator untuk membuat tiga skenario investasi kandang.'),
        native_seed_module(12, 'Farm Management', 18, 'Organisasi dan SOP Farm', 'Management', 'Membangun struktur kerja, briefing, handover, dan SOP yang berjalan di lapangan.',
            "## Orang dan proses\n\nSOP yang baik menjawab siapa melakukan apa, kapan, bagaimana, dengan standar apa, dan apa yang dilakukan jika terjadi deviasi. Briefing singkat dan handover mengurangi informasi yang hilang antar shift.\n\nAudit SOP melalui observasi, bukan hanya tanda tangan.",
            ['Membuat SOP operasional.', 'Membagi tanggung jawab.', 'Menyusun ritme briefing dan handover.'],
            ['SOP harus praktis.', 'PIC dan tenggat harus jelas.', 'Temuan audit harus ditutup.'],
            ['Review SOP kritis.', 'Lakukan briefing harian.', 'Catat temuan dan follow-up.'],
            'Pilih satu SOP kritis dan revisi dengan format tujuan-langkah-standar-koreksi.'),
        native_seed_module(13, 'Advanced Management', 19, 'Troubleshooting Produksi', 'Troubleshooting', 'Menganalisis gap HDP, egg weight, FCR, mortalitas, dan kualitas telur secara sistematis.',
            "## Dari gejala ke sebab\n\nMulai dengan verifikasi data, tentukan kapan gap dimulai, lalu petakan faktor pakan, air, lingkungan, kesehatan, manusia, dan mesin. Jangan mengubah banyak variabel sekaligus karena penyebab akan sulit dibaca.\n\nGunakan evidence dan catatan waktu.",
            ['Membedakan gejala dan akar masalah.', 'Menyusun hipotesis.', 'Menentukan prioritas tindakan.'],
            ['Verifikasi data sebelum tindakan.', 'Perubahan bertahap memudahkan evaluasi.', 'Tindakan perlu indikator hasil.'],
            ['Tentukan baseline.', 'Buat fishbone sederhana.', 'Tetapkan owner tindakan.'],
            'Ambil satu masalah KPI dan buat analisis 5-Why.'),
        native_seed_module(13, 'Advanced Management', 20, 'Root Cause Analysis & Improvement Plan', 'Improvement', 'Mengubah temuan operasional menjadi rencana perbaikan yang terukur.',
            "## Siklus perbaikan\n\nGunakan PDCA: plan, do, check, act. Setiap rencana perlu baseline, target, PIC, tenggat, risiko, dan cara verifikasi. Tindakan yang berhasil distandardisasi; yang gagal dianalisis ulang.\n\nKebiasaan kecil yang konsisten sering mengalahkan program besar yang tidak diawasi.",
            ['Membuat improvement plan.', 'Mengukur efektivitas tindakan.', 'Menstandardisasi perbaikan.'],
            ['Rencana tanpa pengukuran tidak bisa dievaluasi.', 'Target harus realistis dan berbatas waktu.', 'Perbaikan perlu dijaga melalui SOP.'],
            ['Tulis baseline dan target.', 'Review progres mingguan.', 'Update SOP setelah berhasil.'],
            'Buat satu A3 improvement plan untuk menurunkan satu gap KPI.'),
        native_seed_module(14, 'Expert Level', 21, 'Farm Strategy & Decision Making', 'Strategy', 'Mengambil keputusan farm dengan perspektif kapasitas, risiko, pasar, dan profitabilitas.',
            "## Strategi farm\n\nStrategi menghubungkan tujuan bisnis dengan kapasitas kandang, kompetensi tim, teknologi, supplier, pasar, dan risiko. Tidak semua masalah diselesaikan dengan menambah input; sering kali desain proses dan disiplin eksekusi lebih menentukan.\n\nGunakan data untuk menguji asumsi.",
            ['Menetapkan prioritas strategi.', 'Menganalisis risiko dan trade-off.', 'Membuat keputusan yang dapat dieksekusi.'],
            ['Strategi harus punya indikator.', 'Risiko perlu owner dan mitigasi.', 'Keputusan harus dikomunikasikan.'],
            ['Review SWOT farm.', 'Tentukan tiga prioritas.', 'Buat rencana 90 hari.'],
            'Susun strategi 90 hari dengan tiga sasaran, KPI, PIC, dan risiko.'),
        native_seed_module(14, 'Expert Level', 22, 'Continuous Improvement & Capstone', 'Capstone', 'Menggabungkan data, operasional, kesehatan, manusia, dan ekonomi dalam proyek perbaikan farm.',
            "## Capstone\n\nProyek akhir merangkum cara berpikir seorang farm manager: memilih masalah penting, memvalidasi data, mencari akar masalah, merancang tindakan, menghitung dampak ekonomi, dan menjaga hasil melalui standar kerja.\n\nPresentasikan hasil dengan bukti sebelum-sesudah.",
            ['Mengintegrasikan seluruh KPI.', 'Menyusun proyek perbaikan end-to-end.', 'Mempresentasikan hasil dan pembelajaran.'],
            ['Masalah harus spesifik.', 'Dampak harus terukur.', 'Pembelajaran harus ditransfer ke tim.'],
            ['Pilih masalah prioritas.', 'Kumpulkan baseline.', 'Presentasikan hasil dan next step.'],
            'Buat proposal capstone dua halaman: masalah, data, akar masalah, solusi, biaya, dampak, dan rencana kontrol.'),
    ],
    'questions' => [
        native_seed_question(1, 'Apa fungsi utama KPI dalam pengelolaan farm?', ['Menggantikan SOP', 'Membantu keputusan berbasis data', 'Menambah pekerjaan administrasi', 'Menghilangkan kebutuhan supervisi'], 1, 'KPI membantu tim melihat gap dan menentukan tindakan.'),
        native_seed_question(2, 'Mengapa umur ayam penting saat membaca performa?', ['Karena semua umur punya target yang sama', 'Karena target dan kebutuhan berubah menurut fase', 'Karena umur tidak berhubungan dengan produksi', 'Agar data bisa dihapus setiap minggu'], 1, 'Target pertumbuhan, pakan, dan produksi berubah menurut fase.'),
        native_seed_question(3, 'Indikator yang berguna untuk mengecek keberhasilan brooding awal adalah...', ['Crop fill dan perilaku ayam', 'Harga telur saja', 'ROI tahunan', 'Jumlah kendaraan tamu'], 0, 'Crop fill dan perilaku memberi sinyal akses pakan-air dan kenyamanan.'),
        native_seed_question(4, 'Uniformity biasanya menggambarkan...', ['Keseragaman bobot flock', 'Jumlah telur retak saja', 'Konsumsi listrik', 'Harga pakan'], 0, 'Uniformity mengukur proporsi ayam dalam rentang bobot tertentu.'),
        native_seed_question(5, 'Tujuan utama transisi pre-lay yang baik adalah...', ['Membuat perubahan mendadak', 'Menyiapkan ayam masuk produksi secara terkendali', 'Mengurangi akses air', 'Mengabaikan bobot badan'], 1, 'Transisi pakan, cahaya, dan kandang perlu dikendalikan.'),
        native_seed_question(6, 'Egg mass menggabungkan informasi...', ['HDP dan egg weight', 'Mortalitas dan suhu saja', 'Revenue dan cost saja', 'Jumlah karyawan dan luas kandang'], 0, 'Egg mass menggabungkan persentase produksi dan berat telur.'),
        native_seed_question(7, 'Komponen nutrisi yang penting untuk kualitas kerabang adalah...', ['Kalsium dan fosfor', 'Air hujan saja', 'Pasir', 'Disinfektan'], 0, 'Mineral terutama kalsium dan fosfor berperan dalam kerabang.'),
        native_seed_question(8, 'Perubahan konsumsi air sebaiknya dibandingkan dengan...', ['Suhu, pakan, dan kondisi flock', 'Warna dinding saja', 'Jumlah dokumen', 'Nama kandang'], 0, 'Konteks lingkungan dan feed intake membantu membaca perubahan ratio.'),
        native_seed_question(9, 'Pengukuran mikroklimat yang paling relevan dilakukan...', ['Di level ayam pada beberapa titik', 'Hanya di kantor', 'Hanya di luar farm', 'Setahun sekali'], 0, 'Kondisi di level ayam dapat berbeda antar titik kandang.'),
        native_seed_question(10, 'Alarm dan generator pada closed house berfungsi sebagai...', ['Pengaman saat terjadi gangguan', 'Pengganti semua SOP', 'Alat grading telur', 'Pengukur FCR'], 0, 'Kegagalan listrik atau ventilasi dapat menjadi risiko akut.'),
        native_seed_question(11, 'Untuk dugaan penyakit, tindakan yang tepat adalah...', ['Menebak dosis sendiri', 'Mengikuti alur eskalasi dan melibatkan dokter hewan', 'Menghapus catatan', 'Menghentikan air'], 1, 'Diagnosis dan terapi perlu ditangani dokter hewan yang bertanggung jawab.'),
        native_seed_question(12, 'Footbath yang benar harus...', ['Berisi larutan aktif dan dirawat', 'Dibiarkan kering selamanya', 'Hanya dipasang sebagai dekorasi', 'Dipakai untuk menyimpan pakan'], 0, 'Footbath harus aktif, bersih, dan menjadi bagian dari prosedur masuk.'),
        native_seed_question(13, 'Salah satu cara menurunkan telur retak adalah...', ['Memperbaiki handling dan titik collection', 'Mengurangi pencatatan', 'Menaikkan semua suhu', 'Mengabaikan reject'], 0, 'Sumber kerusakan perlu dicari dari nest hingga handling.'),
        native_seed_question(14, 'Data dictionary membantu tim untuk...', ['Menyamakan definisi dan satuan KPI', 'Menghapus data lama', 'Mengganti dokter hewan', 'Menentukan warna logo'], 0, 'Definisi yang sama membuat data dapat dibandingkan.'),
        native_seed_question(15, 'FCR sebaiknya dibaca bersama...', ['Egg mass dan feed intake', 'Warna telur saja', 'Jumlah tamu', 'Luas kantor'], 0, 'FCR adalah perbandingan feed dengan output egg mass.'),
        native_seed_question(16, 'Omzet tinggi dapat tetap menghasilkan profit rendah apabila...', ['Cost driver tidak terkendali', 'Data dicatat rapi', 'SOP berjalan', 'Kualitas membaik'], 0, 'Profit bergantung pada revenue dan seluruh biaya terkait.'),
        native_seed_question(17, 'BEP digunakan untuk memperkirakan...', ['Waktu atau volume saat investasi tertutup', 'Jumlah vaksin', 'Uniformity', 'Kelembapan'], 0, 'BEP menghubungkan investasi dengan margin yang dihasilkan.'),
        native_seed_question(18, 'SOP yang baik menjelaskan...', ['Siapa, apa, kapan, standar, dan koreksi', 'Hanya nama pemilik', 'Hanya harga telur', 'Hanya jadwal libur'], 0, 'SOP operasional harus dapat dijalankan dan diaudit.'),
        native_seed_question(19, 'Langkah awal troubleshooting KPI adalah...', ['Memverifikasi data dan kapan gap dimulai', 'Mengubah semua variabel sekaligus', 'Menghapus baseline', 'Menunggu tanpa catatan'], 0, 'Validasi data dan timeline membantu mempersempit penyebab.'),
        native_seed_question(20, 'PDCA berarti...', ['Plan, Do, Check, Act', 'Price, Data, Cost, Audit', 'Pakan, DOC, Cage, Air', 'Peak, Drop, Change, Age'], 0, 'PDCA adalah siklus perbaikan berkelanjutan.'),
        native_seed_question(21, 'Strategi farm yang baik harus memiliki...', ['Prioritas, indikator, owner, dan mitigasi risiko', 'Target tanpa PIC', 'Satu angka tanpa konteks', 'Keputusan yang tidak dikomunikasikan'], 0, 'Strategi perlu diterjemahkan menjadi eksekusi terukur.', 'hard'),
        native_seed_question(22, 'Ciri capstone yang kuat adalah...', ['Memiliki baseline, solusi, dampak, dan kontrol', 'Hanya opini tanpa data', 'Tidak punya target', 'Mengabaikan biaya'], 0, 'Capstone mengintegrasikan data dan tindakan perbaikan.', 'hard'),
        native_seed_question(0, 'Dalam membaca performa layer, kombinasi yang paling informatif adalah...', ['HDP, egg weight, egg mass, feed intake, dan FCR', 'Warna kandang saja', 'Jumlah rapat saja', 'Harga satu bahan saja'], 0, 'Kombinasi output, input, dan efisiensi memberi gambaran kinerja.'),
        native_seed_question(0, 'Jika HDP turun dan konsumsi air naik, pemeriksaan awal yang masuk akal adalah...', ['Cek suhu, kebocoran, kualitas air, dan kondisi flock', 'Menghapus data produksi', 'Mengurangi akses air', 'Mengubah semua formula tanpa verifikasi'], 0, 'Perubahan air dan produksi perlu dibaca bersama faktor lingkungan dan kesehatan.'),
        native_seed_question(0, 'Sebelum membandingkan FCR dua kandang, pastikan...', ['Periode, satuan, umur, dan definisi data sebanding', 'Warna kandang sama', 'Jumlah supervisor sama', 'Semua data dibulatkan'], 0, 'Benchmark hanya valid jika basis perbandingannya setara.'),
        native_seed_question(0, 'Tindakan koreksi yang efektif seharusnya memiliki...', ['PIC, target, tenggat, dan indikator hasil', 'Nama tanpa tanggal', 'Banyak perubahan tanpa baseline', 'Tidak ada dokumentasi'], 0, 'Rencana yang terukur bisa dipantau dan distandardisasi.'),
        native_seed_question(0, 'Untuk diagnosis penyakit dan dosis obat, aplikasi sebaiknya...', ['Menyarankan konsultasi dokter hewan', 'Memberi dosis pasti tanpa data', 'Mengabaikan withdrawal period', 'Menghapus catatan kesehatan'], 0, 'Asisten membantu analisis awal, sedangkan diagnosis dan terapi perlu dokter hewan.', 'expert'),
        native_seed_question(0, 'Tujuan akhir continuous improvement adalah...', ['Perbaikan terukur yang dipertahankan melalui standar', 'Program besar tanpa evaluasi', 'Mengganti semua orang', 'Menghindari pencatatan'], 0, 'Perbaikan harus menghasilkan standar baru dan kontrol.'),
    ],
];
