// @ts-nocheck
import React from "react";
import { Link, useParams } from "react-router-dom";
import { Badge, Button, Icon, Surface, Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/primitives";
import AapmIcon from "@/components/icons/AapmIcon";
import { useAdminCourse } from "@/lib/useAdminData";
import { AdminError, AdminLoading, AdminPageFrame, AdminUnavailable } from "@/components/admin/AdminPage";

export default function AdminCourseDetail() {
  const { courseId } = useParams();
  const { data: course, isLoading, error, refetch } = useAdminCourse(courseId);

  return (
    <AdminPageFrame title={course?.title || "Course detail"} description="Detail course berasal dari katalog modul yang aktif." actions={<Button asChild variant="outline"><Link to="/admin/courses"><AapmIcon name="arrowLeft" className="h-4 w-4" /> Semua course</Link></Button>}>
      {isLoading ? <AdminLoading label="Memuat struktur course…" /> : error ? <AdminError error={error} onRetry={refetch} /> : <div className="space-y-5">
        <Surface tone="orange" className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><div className="rounded-xl bg-white/70 p-2"><Icon name="course" className="h-6 w-6" /></div><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-lg font-semibold">{course.title}</h2><Badge variant="soft" className="bg-white/70 text-tint-orange-foreground">{course.status === "published" ? "Published" : "Unavailable"}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{course.moduleCount} modul · {course.learnerCount} learner dengan progres</p></div></div><Button type="button" variant="outline" disabled title="Publish belum didukung oleh API native">Publish</Button></Surface>
        <Tabs defaultValue="general"><TabsList className="w-full justify-start overflow-x-auto"><TabsTrigger value="general">General</TabsTrigger><TabsTrigger value="curriculum">Curriculum</TabsTrigger><TabsTrigger value="learners">Learners</TabsTrigger></TabsList><TabsContent value="general" className="mt-4"><Surface className="p-5"><h2 className="text-sm font-semibold">Batas kemampuan V1</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{course.availabilityNote}</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><Surface variant="muted" className="p-4"><div className="text-xs text-muted-foreground">Struktur</div><div className="mt-1 text-xl font-semibold">{course.moduleCount} modul</div></Surface><Surface variant="muted" className="p-4"><div className="text-xs text-muted-foreground">Publish</div><div className="mt-1 text-sm font-semibold">Belum tersedia</div></Surface><Surface variant="muted" className="p-4"><div className="text-xs text-muted-foreground">Re-order</div><div className="mt-1 text-sm font-semibold">Belum tersedia</div></Surface></div></Surface></TabsContent><TabsContent value="curriculum" className="mt-4"><div className="space-y-3">{course.curriculum?.map((level) => <Surface key={level.levelNumber} className="overflow-hidden p-0"><div className="flex items-center gap-3 border-b border-[hsl(var(--surface-border))] bg-surface-subtle px-5 py-4"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-green text-xs font-bold text-white">{level.levelNumber}</div><div><h2 className="text-sm font-semibold">{level.levelName}</h2><p className="mt-0.5 text-xs text-muted-foreground">{level.modules.length} modul</p></div></div><div className="divide-y divide-[hsl(var(--surface-border))]">{level.modules.map((module) => <div key={module.id} className="flex items-center gap-3 px-5 py-3"><AapmIcon name="reorder" className="h-4 w-4 text-muted-foreground/50" /><span className="w-7 text-xs font-semibold text-muted-foreground">{module.moduleNumber}</span><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{module.title}</div><div className="mt-0.5 truncate text-xs text-muted-foreground">{module.category || module.summary}</div></div></div>)}</div></Surface>)}</div></TabsContent><TabsContent value="learners" className="mt-4"><AdminUnavailable title="Course-level enrollment belum tersedia" description="API native menyimpan progres per learner, tetapi belum menyimpan enrollment terpisah per course. Daftar learner tetap tersedia di menu Learners." /></TabsContent></Tabs>
      </div>}
    </AdminPageFrame>
  );
}
